version: "3.8"
services:
  # 1. Database Postgres
  postgres:
    image: postgres:16-alpine
    container_name: uth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: confms_db
    ports:
      - "5435:5432"

  # 2. Redis (Yêu cầu đề bài)
  redis:
    image: redis:alpine
    container_name: uth_redis
    ports:
      - "6379:6379"

  # 3. Backend Java
  backend:
    build: ../backend
    container_name: uth_backend
    ports:
      - "9090:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/confms_db
      SPRING_DATA_REDIS_HOST: redis

  # 4. AI Service
  ai-service:
    build: ../ai-service
    container_name: uth_ai
    ports:
      - "8001:8000"
