version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: uth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: confms_db
    ports:
      - "5435:5432"
    volumes:
      - uth_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: uth_redis
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    container_name: uth_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SERVER_PORT: 8080

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/confms_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # JWT configuration
      APP_JWT_SECRET: ${JWT_SECRET:-put_a_very_long_random_secret_here_min_32_chars_uthconfms2024}
      APP_JWT_EXPIRATION-MS: 86400000

      # Firebase Admin credentials path trong container
      FIREBASE_PROJECT_ID: uth-confms
      FIREBASE_CREDENTIALS: /run/secrets/firebase-sa.json

      # React dev
      CORS_ALLOWED_ORIGINS: http://localhost:5173
    volumes:
      - ../uth-confms-firebase-sa.json:/run/secrets/firebase-sa.json:ro

  ai-service:
    build: ../ai-service
    container_name: uth_ai
    ports:
      - "8001:8000"

volumes:
  uth_pgdata:
